#!/bin/bash

echo "Starting RabbitMQ"
/usr/lib/rabbitmq/bin/rabbitmq-server &

sleep 10

if [ "$CONTAINER_SERVER" == "$MASTER" ]; then
	echo "Running as master"
else
	echo "Joining cluster at $MASTER"
	rabbitmqctl stop_app
	rabbitmqctl reset
	rabbitmqctl join_cluster rabbit@$MASTER
	rabbitmqctl start_app
fi

# Infinite sleep loop to keep docker backgrounding happy
while true; do
	sleep 1
done
